# https://www.techiediaries.com/python-unit-tests-github-actions/
# https://github.com/actions/setup-python

name: 'pytest'
on:
  push:
    branches: ['*']
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Python 3
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run all pytest tests
        run: python -m pytest
